### PR TITLE
Make keyring selectable through arguments

### PR DESCRIPTION
**Pull request by neithernut**
This PR makes the keyring to which the encryption keys are added settable through module arguments.

### CODE REVIEW

**Comment by neithernut** [comment]
I didn't conduct any tests, yet. Documentation is also missing.

**Comment by seebaclo** [comment]
How this option should look like in system-login ?

**Comment by neithernut** [comment]
It would be something like:
```
session     required        pam_e4crypt.so    keyring=_ses
```

**Comment by seebaclo** [comment]
It works, however in case of user keyring, specific uid have to be set:
` session     required        pam_e4crypt.so    keyring=_uid` - doesn't work
` session     required        pam_e4crypt.so    keyring=_uid.999` - works

So in case of multi-user environment `pam_e4crypt.so` should detect correct uid automatically and setting `keyring=_uid` should be enough.

**Comment by neithernut** [comment]
Sounds reasonable. I'll look at how to implement this feature.

**Comment by neithernut** [comment]
You should now be able to specify the user keyring using `@u` instead of `_uid.<num>`. Maybe I'll find some time for testing the changes tomorrow.

**Comment by seebaclo** [comment]
Works for me. Thanks.

**Comment by neithernut** [comment]
This PR might be followed by some cleanup work soonish.

**Pull request merged**
